CREATE TABLE "MEMBER" (
	"ID"	NUMBER(10)		NOT NULL,
	"USERNAME"	VARCHAR2(100)		NOT NULL,
	"PASSWORD"	VARCHAR2(100)		NOT NULL
);

COMMENT ON COLUMN "MEMBER"."ID" IS '멤버들의 식별자';

COMMENT ON COLUMN "MEMBER"."USERNAME" IS '멤버들의 아이디';

COMMENT ON COLUMN "MEMBER"."PASSWORD" IS '멤버들의 비밀번호';

CREATE TABLE "MEMBER_DETAIL" (
	"ID"	NUMBER(10)		NOT NULL,
	"NICKNAME"	VARCHAR2(100)		NULL,
	"TELNUM"	VARCHAR2(20)		NULL,
	"EMAIL"	VARCHAR2(20)		NULL
);

COMMENT ON COLUMN "MEMBER_DETAIL"."ID" IS '멤버들의 식별자';

COMMENT ON COLUMN "MEMBER_DETAIL"."NICKNAME" IS '멤버들의 닉네임';

COMMENT ON COLUMN "MEMBER_DETAIL"."TELNUM" IS '멤버들의 전화번호';

COMMENT ON COLUMN "MEMBER_DETAIL"."EMAIL" IS '멤버들의 이메일';

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"ID"
);

ALTER TABLE "MEMBER_DETAIL" ADD CONSTRAINT "PK_MEMBER_DETAIL" PRIMARY KEY (
	"ID"
);

ALTER TABLE "MEMBER_DETAIL" ADD CONSTRAINT "FK_MEMBER_TO_MEMBER_DETAIL_1" FOREIGN KEY (
	"ID"
)
REFERENCES "MEMBER" (
	"ID"
);

